"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os, json
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

secret_file = os.path.join(BASE_DIR, 'secrets.json') 

with open(secret_file) as f:
    secrets = json.loads(f.read())

def get_secret(setting, secrets=secrets): 
# secret 변수를 가져오거나 그렇지 못 하면 예외를 반환
    try:
        return secrets[setting]
    except KeyError:
        error_msg = "Set the {} environment variable".format(setting)
        raise ImproperlyConfigured(error_msg)

SECRET_KEY = get_secret("SECRET_KEY")
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

DJANGO_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

PROJECT_APPS = [
    'posts',
    'accounts',
]

THIRD_PARTY_APPS = [
    "corsheaders",
    "rest_framework",

]

INSTALLED_APPS = [

]

INSTALLED_APPS = DJANGO_APPS + PROJECT_APPS + THIRD_PARTY_APPS

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware', # 반드시 가장 위쪽에 추가
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    #'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'config.middleware.RequestLoggingMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

AUTH_USER_MODEL = 'accounts.User'

# 인증 관련 요청(쿠키, 세션 등)을 허용
# 예를 들어 브라우저가 백엔드 서버로 쿠키를 전송하거나, 백엔드에서 쿠키를 응답으로 보낼 수 있음
CORS_ALLOW_CREDENTIALS = True

# 서버로 요청 보낼 수 있는 도메인들 정의
# 여기에서의 localhost는 EC2 인스턴스의 로컬환경이 아니라 프론트엔드 개발 로컬 환경 의미
# 3000 포트는 프론트엔드 React 애플리케이션의 포트 번호
# 추후 프론트엔드에서 웹 페이지 배포 후 도메인 매핑했다면 해당 도메인 추가 필요
CORS_ALLOWED_ORIGINS = [ 
    "http://localhost:3000",
    "http://127.0.0.1:3000",
]

import logging
# 로그를 저장할 디렉토리가 없으면 자동으로 생성
LOG_DIR = BASE_DIR / "logs"
if not LOG_DIR.exists():
    LOG_DIR.mkdir(parents=True, exist_ok=True)

#서버로 들어오는 모든 http 요청 로깅하기
#로그에 시간, 로그레벨, 요청 url 포함하기
#warning 이상 에러는 errors.log로 따로 로깅하기
LOGGING = { 
    "version": 1, #the dictConfig format version
    "disable_existing_loggers": False,

    #formatters는 로그 메시지의 형식을 정의하는 부분
    "formatters": {
        "verbose": {# 로그 메시지의 형식을 자세하게 정의하는 포맷터
            "format": "[{asctime}] {levelname} [{url}] {message}", # extra로 전달된 url을 포함하도록 수정
            "style": "{", #로그 메시지에서 중괄호 {}를 사용하여 포맷팅하도록 지정
        },
    },

    "handlers": {
        
        "console": {
            "formatter": "verbose", # verbose 포맷터 사용
            "class": "logging.StreamHandler",
            "level": "INFO", # INFO 이상의 로그만 기록
        },
        
        "warning_file": { 
            "class": "logging.FileHandler",
            "filename": BASE_DIR / "logs" / "errors.log",   # 로그를 저장할 파일 이름 #logs 폴더는 프로젝트 루트 디렉토리에 생성됨
            "level": "WARNING", # WARNING 이상의 로그만 기록
            "formatter": "verbose",
        },

        "file": {
            "class": "logging.FileHandler",
            "filename": BASE_DIR / "logs" / "all.log",   # 로그를 저장할 파일 이름 #logs 폴더는 프로젝트 루트 디렉토리에 생성됨
            "level": "INFO", # INFO 이상의 로그만 기록
            "formatter": "verbose", # verbose 포맷터 사용
        },
    },

    "loggers": {
        #"django": { # Django 프레임워크에서 발생하는 로그를 처리하는 로거
        #    "handlers": ["console", "warning_file", "file"], # 로그 메시지를 처리할 핸들러 지정
        #    "level": "INFO", # INFO 이상의 로그만 처리
        #    "propagate": True, # 상위 로거로 로그 메시지 전파 여부
        #},
        "http.request": { # Django의 HTTP 요청 처리와 관련된 로그를 처리하는 로거
            "handlers": ["console", "warning_file", "file"], # 로그 메시지를 처리할 핸들러 지정
            "level": "INFO", # INFO 이상의 로그만 처리
            "propagate": False, # 상위 로거로 로그 메시지 전파 여부
        },
    },

}