# Generated by Django 6.0.3 on 2026-03-25 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_remove_category_post_category_post'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category_Post',
            new_name='Post_Category',
        ),
    ]
