# Generated by Django 6.0.3 on 2026-03-25 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_rename_category_post_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='post',
            field=models.ManyToManyField(to='posts.post'),
        ),
        migrations.DeleteModel(
            name='Post_Category',
        ),
    ]
