# Generated by Django 6.0.3 on 2026-03-31 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_category_post_delete_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='post',
            field=models.ManyToManyField(related_name='categories', to='posts.post'),
        ),
    ]
